language: node_js
sudo: true
node_js: 10
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_install:
- export PATH=$PWD/node_modules/.bin:$PATH
install:
- npm install
- npm i polymer-cli
script:
- npm run lint
- npm run test
after_success:
- ' [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" == "master" ] && npm
  run publish:cdn '
- ' frauci-update-version -d=skip && export TRAVIS_TAG=$(frauci-get-version) '
deploy:
  provider: releases
  api_key: "$GITHUB_RELEASE_TOKEN"
  on:
    tags: true
env:
  global:
  - REPO_NAME=d2l-activity-exemptions
  - OWNER_NAME=Brightspace
  - secure: ZZ4ZmlKGeDbDW6TWbNK6rCQzBGM6RvrnlVdCnf+qisYksU4wFvybJ8CDg8jakrK6HE3o+1aw8N3pzlImThQjcQsoiXCrTjLbzBxKvdOr2vZF8R3Z0Tw2Ckq2SxkyzwyZVJWZwbAOCIedi6kz3cEWK7RSc1vJPAaKiULI8lnb8WENU/AztTKjqHdRUGrJQUBYvIsHjXzJs/vb8x6V61K2nSVUyttV6ID3RtTqvNZsUgaAG4UZNucNgN5kL2/nlcXYN8WfWIsVX7FunSCaiRm4JQy4q5g1uQ/SK4qm1QJt+DQ/l0xiibJhthWFIDsMjS7922ELNbXXEQp+9r0p0squSNTX804qqkaDkkkJ+oLA7MjSTHakfOP66x3zTGpgAmDDDW4k6odxWZ6nOBLTS9BUcYLloll+CZnLS0fRNEOmS8c0JTV6rUtVu0z0kgEJ2ZhJkOBa7fQ0j4Vjk9luk2VCZNMuCYgufSziyruOWJpaJNPOJby8n+5koGqA1bxcv7tP13OYaB7sfEWBbps67fsjfwp1bAWA5GFkjkT7Oe603sxGGb5aDXNthFdphswGoKSCJ4m9+Uf00PrKywXpw2k264PRYAwa5E0zgs2kDADRDqzkSuXOhxfKiZKzdKKks87hgG5b1i0AdnBL3U6FqGgTrf8vOTpb4l8K5lgFI/6wHog=
  - secure: N38oF+gcE9QUt0r4ptQf1/E8T6J7dXMB2kKhHhtBdEWAJd8lQpUuqB9mHuzvUHlt/NDSG2IAotqHieZgB9nfi7raoUscDDYUR2fPYFBYavhrrQEX0v74nNPofi+ch4N0XAQR33YNeooFystT+new4CSxeahkQWCxOTUQ4iJHOUTNN/3UMNbIpbYpV/4npqR61VDWC6vRp4gLvwx6wig+gdzizYHrOVazMwi9FMHK95mrgnlVgut1d5/uCyC3d/KNQ91nMcwiSbTDmywmfHLM57Nn5CGRUPf+hD10vD+WlM6+J064XdrIoaSoLCofdUZnmsCPIxvXRQJe1gTUBfiXZ9Rayow6/EjDXtKtXa/mdaVGu0wuvDrbTepKow6tHXeAg84ixEMG/HvlJiblOcGrKskQJvbXIybGXTUzsGlW19gJpSimee9CZonKEOtNBu3iBpFnvOY/hs3UELeq0AeXn8Li7Q/4QvLaWzODfJgoks4X84N7B0DzScmqDOXdWqehcdM5l60nMdl/FSo2XprE6YO7e5s6upPgyE80fPavjQaWHCZr/NV4dQoQU/PMG5qCpwny1otKZ6+tboIlL7LOsZXvxzKcGPpVtjztNcdVh0oSo/RiuPs+mIxKLwNvBMz1SNNpuHH+sOEJjySTtN+VUTAIf8XMR7NGC++c4Rt7MtQ=
