language: node_js
sudo: true
node_js: 8
dist: trusty
addons:
    apt:
        sources:
            - google-chrome
        packages:
            - google-chrome-stable
before_install:
    - export PATH=$PWD/node_modules/.bin:$PATH
install:
    - npm install
script:
    - npm run lint
    - npm run test