language: node_js
sudo: true
node_js: 8
dist: trusty
cache:
    directories:
    - node_modules
    - bower_components
addons:
    firefox: latest
    apt:
        sources:
            - google-chrome
        packages:
            - google-chrome-stable
before_install:
    - export PATH=$PWD/node_modules/.bin:$PATH
install:
    - npm install
    - npm run update:all
script:
    - npm run lint
    - xvfb-run wct
